[package]
name = "cobhan-demo-lib"
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = "0.13.0"
cobhan = { path = "../cobhan" }
rand = "0.8.4"
serde_json = "1.0.68"

[lib]
name = "plugtest"
crate-type = ["rlib", "cdylib"]

[features]
cobhan_debug = []
