[package]
name = "cobhan"
version = "0.1.0"
edition = "2018"

[dependencies]
libc = "0.2.103"
serde_json = "1.0.68"
tempfile = "3.2.0"

[lib]
name = "cobhan"
crate-type = ["rlib"]

[features]
cobhan_debug = []
