name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-buster-rust:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Buster
      run: ./build-buster-rust.sh
      working-directory: library
  build-bullseye-rust:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Bullseye
      run: ./build-bullseye-rust.sh
      working-directory: library
  build-alpine-rust:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Alpine
      run: ./build-alpine-rust.sh
      working-directory: library
  build-macos-rust:
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build MacOS
      run: ./build-macos-rust.sh
      working-directory: library
  build-buster-go:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Buster
      run: ./build-buster-go.sh
      working-directory: library
  build-bullseye-go:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Bullseye
      run: ./build-bullseye-go.sh
      working-directory: library
  build-alpine-go:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Alpine
      run: ./build-alpine-go.sh
      working-directory: library
  build-macos-go:
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build MacOS
      run: ./build-macos-go.sh
      working-directory: library
