name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: 'ubuntu-latest'
    steps:

  build-bullseye-rust:
    timeout-minutes: 5
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Bullseye Rust
      run: ./build-bullseye-rust.sh
      working-directory: library
    - name: Create github release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: v0.1
      run: ./create-release.sh
    - name: Upload Bullseye Rust
      run: ./upload-artifact.sh rust/libcobhandemo/output/libcobhandemo.so
      working-directory: library
  build-macos-rust:
    timeout-minutes: 5
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build MacOS
      run: ./build-macos-rust.sh
      working-directory: library
  build-bullseye-go:
    timeout-minutes: 5
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Bullseye
      run: ./build-bullseye-go.sh
      working-directory: library
  build-macos-go:
    timeout-minutes: 5
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build MacOS
      run: ./build-macos-go.sh
      working-directory: library
