name: Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-buster:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Buster
      run: ./build-buster.sh
      working-directory: library
  build-bullseye:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Bullseye
      run: ./build-bullseye.sh
      working-directory: library
  build-alpine:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build Alpine
      run: ./build-alpine.sh
      working-directory: library
  build-macos:
    runs-on: 'macos-latest'
    steps:
    - uses: actions/checkout@v2
    - name: Build MacOS
      run: ./build-macos.sh
      working-directory: library
