name: Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Install gcc-go
      run: sudo apt-get install -y gccgo
    - uses: actions/checkout@v2
    - name: Build Rust
      run: ./build-debug.sh
      working-directory: library/rust/libplugtest
    - name: Build Go
      run: ./build-debug.sh
      working-directory: library/go/libplugtest
