name: Debug

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'    
    - uses: actions/checkout@v2    
    - name: Install gcc-go
      run: ./install-gccgo.sh
      working-directory: library/go/libplugtest
    - name: Build Go
      run: ./build-debug.sh
      working-directory: library/go/libplugtest
    - name: Build Rust
      run: ./build-debug.sh
      working-directory: library/rust/libplugtest
    - name: Build Go-Cobhan-Alpine
      run: ./alpine.sh
      working-directory: library/go/cobhan
